server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/viewdb
    username: root
    password: 123456789Root@
    driver-class-name: com.mysql.cj.jdbc.Driver
  

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernat:
      dilect: org.hibernate.dialect.MySQL8Dialect
      
      
      
      
      
      
      
      
      
      
      